export const allProducts = [
  {
    id: 1,
    title: "Classic Mixed Fruit Jam",
    subtitle: "Happy Jam Originals",
    price: "₹199",
    unit: "per jar",
    image: "/images/Classic-Mixed-Fruit-Jam.png",
    category: "Jam",
    rating: 4.8,
    reviews: 1204,
  },
  {
    id: 2,
    title: "Extra Crunchy Peanut Butter",
    subtitle: "High Protein",
    price: "₹299",
    unit: "per jar",
    image: "/images/Extra-Crunchy-Peanut-Butter.png",
    category: "Peanut Butter",
    rating: 4.9,
    reviews: 3512,
  },
  {
    id: 3,
    title: "Mango Pickle",
    subtitle: "Traditional Recipe",
    price: "₹149",
    unit: "per jar",
    image: "/images/mango-pickle.png",
    category: "Pickle",
    rating: 4.7,
    reviews: 892,
  },
  {
    id: 4,
    title: "Chocolate Peanut Butter",
    subtitle: "Guilt-free Dessert",
    price: "₹349",
    unit: "per jar",
    image: "/images/peanut-butter-choco.png",
    category: "Peanut Butter",
    rating: 4.9,
    reviews: 4108,
  },
  {
    id: 5,
    title: "Pickle Trio Combo",
    subtitle: "Mango & Lemon",
    price: "₹399",
    unit: "combo pack",
    image: "/images/Mango,Lemon&Tender-Mango-Pickle-Combo.png",
    category: "Combo Pack",
    rating: 4.6,
    reviews: 356,
  },
  {
    id: 6,
    title: "PB Choco & Crunchy Combo",
    subtitle: "Value Pack",
    price: "₹599",
    unit: "combo pack",
    image: "/images/Peanut-Butter-Chocolate&Crunchy-Combo.png",
    category: "Combo Pack",
    rating: 4.8,
    reviews: 641,
  },
  {
    id: 7,
    title: "Double Choco PB Combo",
    subtitle: "Value Pack",
    price: "₹649",
    unit: "combo pack",
    image: "/images/Peanut-Butter-Two-Chocolate-Combo.png",
    category: "Combo Pack",
    rating: 4.7,
    reviews: 289,
  },
  {
    id: 8,
    title: "No Added Sugar PB Combo",
    subtitle: "Healthy Choice",
    price: "₹549",
    unit: "combo pack",
    image: "/images/Two-Peanut-Butter-No-Added-Sugar&Salt-Combo.png",
    category: "Combo Pack",
    rating: 4.8,
    reviews: 417,
  }
];
